export {default as Home} from "../pages/Home";
// import { default as Chasupport} from "./Chasupport";
export { default as CheckOutPayment} from "./CheckOutPayment";
// import { default as EditProfile} from "./EditProfile";
// import { default as FilterTecnicos} from "./FilterTecnicos"; 
export { default as Footer} from "./Footer";
// import { default as FormAddTicket} from "./FormAddTicket";
// import { default as Login} from "./Login";
// import { default as MyTickets} from "./MyTickets";
// import { default as Profile} from "./Profile";
// import { default as QuestionAndAnswer} from "./QuestionAndAnswer";